name: Pre-release-checks
on: [push]

jobs:
  Pre-release-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch the current master
      uses: actions/checkout@master
      with:
        ref: master
        path: master
    - name: Fetch the original template
      uses: actions/checkout@master
      with:
        ref: template
        path: template
    - name: exam tree
      id: exam-tree
      uses: bo-sfl/my-hello-world-action@prod