name: Pre-release-checks
on: [workflow_dispatch]

jobs:
  Pre-release-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch the current master
      uses: actions/checkout@master
      with:
        ref: master
        path: master
    - name: Fetch the original template
      uses: actions/checkout@master
      with:
        ref: template
        path: template
    - name: exam tree
    　id: pre_release_check
      uses: bo-sfl/my-hello-world-action@prod
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Post Content :rocket:'
    - name: TODO and commented out code checker
      uses: nickssmith/TODO_and_CommentedCode_Check@1.1