name: Pre-release-checks
on: [workflow_dispatch]

jobs:
  Pre-release-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch the current master
      uses: actions/checkout@master
      with:
        ref: master
        path: master
        lfs: False

    - name: Fetch the original template
      uses: actions/checkout@master
      with:
        ref: template
        path: template
        lfs: False

    - name: Release check
      id: release_check
      uses: bo-sfl/my-hello-world-action@prod

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ steps.release_check.outputs.message }}